### ISSUE TITLE
Certain attributes should be able to inherit their default value from a parent

### ISSUE THREAD

**Issue by gjost** [densho/ddr-cmdln#104]
More attribute inheritance of default values for new files and/or entities in DDR Editor UI
Set a default value based on parent collection, but do not link inheritance to parent collection. courtesy line, contributing institution, digitizer, digitizing institution

Update: The desired behavior is that when a *new* object is created, the default values for inheritable fields should be values from the parent object, *not* those from `ddr-defs.

**Comment by gjost** [comment]
I don't quite know what this feature is supposed to do.  Could you describe it a bit more?

**Comment by gjost** [comment]
Can you please be more specific?
There are no fields named "courtesy line"
"contributor" AKA contributing institution is already inheritable.
I made digitizer and digitizing institution inheritable, but this only means that segments will inherit from entities - there is no related field in colleciton.

**Comment by GeoffFroh** [comment]
From original issue (https://github.com/densho/ddr-local/issues/241)

`collection.contributor` --> `entity.contributor`
`collection.prefercite` --> `entity.credit`

**Comment by gjost** [comment]
> collection.contributor --> entity.contributor
> collection.prefercite --> entity.credit
Already got those ones.  I'm wondering what you'd like to do about "courtesy line" and the "digitizer*" fields.
"Courtesy line" doesn't exist anywhere in defs.
Collection has no "digitizer" fields.  File has `digitize_person` but not `digitize_organization`.

**Comment by GeoffFroh** [comment]
prefercite/credit are the courtesy line

**Comment by GeoffFroh** [comment]
file.digitize_person inherits from entity.digitize_person

**Comment by gjost** [comment]
Fixed as of commit 99f16aa.
