### ISSUE TITLE
OSError when trying to add collection files

### ISSUE THREAD

**Issue by gjost** [densho/ddr-cmdln#117]
In at least one `ddr-local` install, adding a new Entity results in an `OSError` because the function is mistakenly trying to add `collection.json` and `ead.xml` to the repository and those files are not there.  Or perhaps `CWD` is not at the collection root so they don't appear to be there.  In any case, they don't need to be added when creating a new Entity.

**Comment by gjost** [comment]
Django error page from the affected machine: /home/gjost/downloads/densho-1000newobj.html

**Comment by gjost** [comment]
Try this with a segment

**Comment by gjost** [comment]
In [`DDR.models.entity.py:new`](https://github.com/densho/ddr-cmdln/blob/0c6c299c062b10426288477c760bd9f5c926eb76/ddr/DDR/models/entity.py#L329) the `updated_files` arg to `DDR.commands.entity_create` should be empty.  Currently it's
```
             [collection.json_path_rel, collection.ead_path_rel],
```
Maybe that function was cut-and-pasted from `Collection.new` without modifying it for `Entity`?

The weird thing is that it works on other machines in the HQ.

**Comment by GeoffFroh** [comment]
The affected repo (ddr-densho-1000) was missing `ead.xml` at the root; adding the file addressed the issue. Not important to refactor at the present.
