### ISSUE TITLE
ddrimport file segment

### ISSUE THREAD

**Issue by sarabeckman** [densho/ddr-cmdln#121]
[ddrimport file segment error.txt](https://github.com/densho/ddr-cmdln/files/2886845/ddrimport.file.segment.error.txt)
[ddr-csujad-30-master-children-20190220.xlsx](https://github.com/densho/ddr-cmdln/files/2886861/ddr-csujad-30-master-children-20190220.xlsx)

I encountered this bug while importing master files for ddr-csujad-30 on my local VM. The CSV I was using was for three Visual History entities and I was adding the master file to the segment. 

ddrimport correctly identified the model as segment but then my CSV failed the validation check and listed I didn't have the correct headers (it lists the headers for an entity csv). As you can see in the text document with the error output I used the comman ddrimport file. 

I have been able to successfully ingest the files through the webui.

**Comment by gjost** [comment]
> I have been able to successfully ingest the files through the webui.

Do you mean that you have successfully imported the files individually?  Or that you used the CSV import feature in the web UI?

Have you guys imported files from similar spreadsheets in the past?  Did it work before but something changed, or did it never work?

**Comment by gjost** [comment]
FWIW when I've tested file importing in the past I've started by exporting a blank CSV and editing that.
`ddrexport file --blank /var/www/media/ddr/ddr-csujad-30/ /tmp/ddr-csujad-30-files.csv`

Can you give that a try and let me know if it works for you?

**Comment by gjost** [comment]
Fixed as of commit 1ce0967.
