### ISSUE TITLE
Template switching not working on AV entities

### ISSUE THREAD

**Issue by sarabeckman** [densho/ddr-cmdln#123]
When indexing ddr-csujad-29, ddr-csujad-30, and ddr-csujad-31 using ddrlocal-develop_2.6.8w I noticed the AV entities weren't displaying as we had discussed. 

The 'download transcript' button wasn't on the page etc. Looking closer there is no `template` attribute https://ddrstage.densho.org/api/0.2/ddr-csujad-29-54/ (see ddr-csujad-28-1 for comparison  https://ddrstage.densho.org/api/0.2/ddr-csujad-28-1/)

**Comment by GeoffFroh** [comment]
Sara tested indexing with ddr-csujad-29 and ddr-csujad-28. The indexer seemed to add the `template` attribute for ddr-csujad-28 (see link above), but did not for ddr-csujad-54. 

Both entities are `type` = `av`, with a single mezzanine file with `mimetype` = `audio/mpeg`

see: ddr-csujad-28-1-mezzanine-93bba06d9c.json and ddr-csujad-29-54-mezzanine-66b5f55aaf.json

**Comment by gjost** [comment]
When indexing objects for publication, the `template` attribute is added in [DDR.models.common line 395](https://github.com/densho/ddr-cmdln/blob/master/ddr/DDR/models/common.py#L395).  This line is only executed if the object has a corresponding record at Internet Archive (see [line 387](https://github.com/densho/ddr-cmdln/blob/master/ddr/DDR/models/common.py#L387)).

With the current code, if records are not uploaded to IA then it is impossible for objects to have an A/V template.

**Comment by GeoffFroh** [comment]
Confirmed IA-dependent behavior. Will leave as is for now.
