### ISSUE TITLE
Custom access file import/update

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-cmdln#125]
Access files are automatically created at binary ingest time in the current workflow. If a method for creating a derivative thumbnail is not supported for the ingested file type (e.g., mp3, mp4, html), the access file is not created and added to the repo's git-annex. This can cause problems later if the file is selected as the signature for an entity or collection. 

In the case of VH-type materials, we have worked around this limitation with custom display logic in the ddr-public front-end; however, this method is not flexible. 

File.New needs an option to accept a separate image file along with the original binary that can be used as the access file. This is especially important when creating new external files. Note that it would have the same ddr file id name of the original, with `-a.jpg` appended. 

This functionality also needs to support **replacing** existing access files.

**Comment by gjost** [comment]
See [Custom access files UI](https://github.com/densho/ddr-cmdln/issues/126)

**Comment by gjost** [comment]
- [ ] (ddr-cmdln) File.ingest
- [ ] (ddr-cmdln) batch import
- [ ] (ddr-cmdln) batch update
- [ ] (ddr-local) Regular new-file form
- [ ] (ddr-local) External new file form
- [ ] (ddr-local) API
- [ ] (ddr-cmdln) ddrindex publish
