### ISSUE TITLE
ddr import error when external_url and access_path fields filled

### ISSUE THREAD

**Issue by pkikawa** [densho/ddr-cmdln#130]
error with `external_url` _and_ `access_path`. was _not_ seeing this behavior without the `access_path` field filled

[AttributeError at _ui_collection_ddr-testing-40168_import_files_.txt](https://github.com/densho/ddr-cmdln/files/3014460/AttributeError.at._ui_collection_ddr-testing-40168_import_files_.txt)

**Comment by pkikawa** [comment]
resolved. problem was between the keyboard and chair on my end

**Comment by pkikawa** [comment]
[ddrimport_file_traceback.txt](https://github.com/densho/ddr-cmdln/files/3040888/ddrimport_file_traceback.txt)

**Comment by pkikawa** [comment]
i think this is related to the line breaks that we were seeing in libre office. we saw something similar before with topics which is why we moved to the `--` rather than `;`?

**Comment by gjost** [comment]
Can you upload a copy of the CSV you're trying to import?  I can't replicate it if I don't know what the inputs are.

**Comment by pkikawa** [comment]
[ddr-testing-40173-objects.zip](https://github.com/densho/ddr-cmdln/files/3055777/ddr-testing-40173-objects.zip)

**Comment by gjost** [comment]
I get an error when importing `ddr-testing-40173-objects.csv` but it's a totally different one from `ddrimport_file_traceback.txt`.
```
$ ddrimport entity /tmp/ddr-testing-40173-objects.csv /var/www/media/ddr/ddr-testing-40173/
...
2019-04-08 12:32:53,652 INFO     Validating headers
2019-04-08 12:32:53,653 ERROR    Bad headers
2019-04-08 12:32:53,653 ERROR    *
2019-04-08 12:32:53,653 ERROR    *
2019-04-08 12:32:53,654 ERROR    FAIL
2019-04-08 12:32:53,654 INFO     Validating rows
2019-04-08 12:32:53,659 INFO     ok
2019-04-08 12:32:53,660 ERROR    FAIL
...
```

Also, the issue is about importing files, but since you reopened it everything is about importing entities.

**Comment by pkikawa** [comment]
I am having trouble replicating this error. gimmie a sec

**Comment by pkikawa** [comment]
what's the error you get when importing that test csv?

**Comment by gjost** [comment]
> what's the error you get when importing that test csv?

The last block of code is what I see. (note: edited out a bunch of lines, just showing the part where it fails)

**Comment by pkikawa** [comment]
hmmm. i am still unable to replicate this so it probably _was_ user error (mine) initially. if i cannot replicate this within a couple of hours i will reclose this issue. _again_

**Comment by pkikawa** [comment]
cannot replicate
