### ISSUE TITLE
ddrimport does not commit changes and does not update the idservice

### ISSUE THREAD

**Issue by pkikawa** [densho/ddr-cmdln#133]
importing entities.csv results in the changes to entity.json, mets.xml and changelog files are uncommitted and the idservice is not updated. 

[ddrimport_ddr-testing-40205-entities.log](https://github.com/densho/ddr-cmdln/files/3036195/ddrimport_ddr-testing-40205-entities.log)

**Comment by gjost** [comment]
IIRC this was a design decision.  The idea was that you run ddrimport then examine the changes and then commit manually.  Am I forgetting something?

**Comment by pkikawa** [comment]
intentional design decision.
