### ISSUE TITLE
ddr-signatures crashes with binary in administrative tab

### ISSUE THREAD

**Issue by sarabeckman** [densho/ddr-cmdln#134]
Today I tried to run `ddr-signatures` on `ddr-densho-379` and it crashed. I was running it on my local VM 2.7.1 master. The traceback is in the text doc. Basically, the expectation was 'administrative'. I did have a file in the administrative tab in `ddr-densho-379-1`. 

There is a workaround currently - I just deleted the binary file from the administrative tab and ran the command again and it worked as expected.

[ddr-signatures-traceback.txt](https://github.com/densho/ddr-cmdln/files/3060847/ddr-signatures-traceback.txt)

**Comment by gjost** [comment]
Looks like it doesn't recognize the "administrative" keyword.  Apparently there are still a few places where I hard-coded file roles.

**Comment by pkikawa** [comment]
Bug still present on DEV 283g

**Comment by gjost** [comment]
Fixed in ddr-cmdln commit a605feb for package ddrlocal-develop_2.8.3j.

**Comment by GeoffFroh** [comment]
See https://github.com/densho/ddr-cmdln/issues/151
