### ISSUE TITLE
child entites not appearing in webui child list (not being added to parent entity.json "children")

### ISSUE THREAD

**Issue by pkikawa** [densho/ddr-cmdln#138]
parent and child entities added via webui. parent entity.json does not show child entity. child entity does not appear in webui child list

[ddr-testing-40180-1.zip](https://github.com/densho/ddr-cmdln/files/3070493/ddr-testing-40180-1.zip)
[local.log](https://github.com/densho/ddr-cmdln/files/3070508/local.log)
addfile [ddr-testing-40180-1.log](https://github.com/densho/ddr-cmdln/files/3070514/ddr-testing-40180-1.log)

**Comment by pkikawa** [comment]
MAv280

**Comment by gjost** [comment]
> MAv280

Does this mean `ddrlocal-master v2.8.0`?

**Comment by pkikawa** [comment]
yes

**Comment by GeoffFroh** [comment]
According to @pkikawa, the data issue has been fixed. I.e., the `children` list in the parent entity is properly updated upon creation of a child entity.

However, the webui of the parent entity is still not displaying the new child entity in the list. (Though the number of children displayed in the tab is updating as expected.)

**Comment by gjost** [comment]
Yep this should be fixed in develop as of commit 4eb4ec7fd3.

**Comment by gjost** [comment]
Ack.  The *data* part was fixed in the previous named commit but templates had to be updated.  That's fixed as of commit  e695087.

**Comment by gjost** [comment]
Fixed the UI in commit 85439e4dd5 and e05b841014.
