### ISSUE TITLE
binary display not functioning properly.

### ISSUE THREAD

**Issue by pkikawa** [densho/ddr-cmdln#147]
2.8.3b DEV

webui tabs are showing correct number of binaries (mostly - see NOTE), but do not list them correctly (see bellow)
![binariesnotshowing1](https://user-images.githubusercontent.com/28398832/56999178-fd2c0b80-6b62-11e9-8f1a-85bff2690914.PNG)

binaries appear to be created correctly and added to the parents entity json (see examples in ddr-testing-40219-1 entity.json)
[ddr-testing-40219.zip](https://github.com/densho/ddr-cmdln/files/3133477/ddr-testing-40219.zip)

setting binary as object/collection signature works. binaries are accessible via webui (fullsize and access files downloading normally), but editing and saving the data results in this error:
[Exception at _ui_file_None_.txt](https://github.com/densho/ddr-cmdln/files/3133436/Exception.at._ui_file_None_.txt)
with failure message :InvalidInputException("Could not grok Identifier input: {'url': None, 'path': None, 'parts': None, 'id': None, 'base_path': '/var/www/media/ddr'}",)
    the change is saved, but the change does NOT get staged for commit.

NOTE: adding a binary (for example a .pdf to Administrative) to a child entity causes the parent's Administrative tab to show that there is a binary present (see bellow)
![childentitiesShowingInParentTab](https://user-images.githubusercontent.com/28398832/56999816-b095ff80-6b65-11e9-8853-4498344ebe17.PNG)
in the above example i added a .pdf to ddr-testing-40219-1-2 Administrative. i had not added an Admin binary to ddr-testing-40219-1.

**Comment by pkikawa** [comment]
addon note - I am seeing this behavior in pre-existing collections 
![olderColelctionBehaviro](https://user-images.githubusercontent.com/28398832/57000053-ca841200-6b66-11e9-9c8c-40083bfa2adf.PNG)

**Comment by gjost** [comment]
This is an error in the function that reads the entity.json and packages the data for displaying this page.  I believe fixed this exact thing but it looks like it didn't get into that package.

**Comment by gjost** [comment]
Should be fixed as of commit 85439e4dd5.
