### ISSUE TITLE
deleting a child entity succeds, but there is no git status update

### ISSUE THREAD

**Issue by pkikawa** [densho/ddr-cmdln#150]
no success message. no failure message. just no messages. backend is clean - no unstaged commits, no uncommitted changes.

**Comment by gjost** [comment]
Fixed in ddr-local commit d1087c4 for package ddrlocal-develop_2.8.3j.

**Comment by GeoffFroh** [comment]
@pkikawa: please verify whether behavior is still present in 2.8.4MA; if fixed, then you can close this issue.

**Comment by pkikawa** [comment]
resolved. 284MA
