### ISSUE TITLE
ddr-signatures not writing to files when status == inprocess or public == 0

### ISSUE THREAD

**Issue by sarabeckman** [densho/ddr-cmdln#151]
Ran `ddr-signatures` against `ddr-densho-397` using my local VM running Master 2.8.4. It didn't write anything to the files.  
[ddr-signatures_output.txt](https://github.com/densho/ddr-cmdln/files/3164013/ddr-signatures_output.txt)

**Comment by GeoffFroh** [comment]
@sarabeckman reports that the functionality works when invoked from the webui (button on file detail page).

**Comment by GeoffFroh** [comment]
(This is not a critical bug for 2.8.4 master. Barring other issues, we can deploy 2.8.4 package to production.)

**Comment by GeoffFroh** [comment]
Tested against ddr-densho-379 and ddr-densho-397. Left `signature` empty intentionally in ddr-densho-379 to make certain there were changes to make.

**Comment by gjost** [comment]
> Left signature empty intentionally in ddr-densho-379 to make certain there were changes to make.

The collection's status is "inprocess".  A small number of entity records are marked non-public.  The signature chooser currently only chooses signatures for items that are public and completed.  Do we want to revise this behavior?

OBJECT ID  (STATUS, PUBLIC)
ddr-densho-379  (inprocess, 1)
ddr-densho-379-207  (completed, 0)
ddr-densho-379-206  (completed, 0)
ddr-densho-379-205  (completed, 0)
ddr-densho-379-204  (completed, 0)
ddr-densho-379-203  (completed, 0)
ddr-densho-379-202  (completed, 0)

**Comment by GeoffFroh** [comment]
No. Signatures should always be created — they are used in the editor interface all the time by the archivists. No signatures == more useless clicking.

**Comment by gjost** [comment]
Got it, will change the behavior.

**Comment by gjost** [comment]
Fixed in ddr-cmdln commit 964bd4e for package ddrlocal-develop_2.8.4a or later.

**Comment by GeoffFroh** [comment]
@pkikawa, please test, then close this issue.

**Comment by pkikawa** [comment]
tested and working on 284aDEV

**Comment by pkikawa** [comment]
working 286MA
