### ISSUE TITLE
ddrimport should ignore columns with headers in ALL CAPS

### ISSUE THREAD

**Issue by gjost** [densho/ddr-cmdln#153]
DDR objects already have a notes field into which users can enter metadata that doesn't fit elsewhere.

This change would enable users to add notes to spreadsheets that will be ignored by the importer.  This would enable users to add fields with e.g. metadata about the editing or importing process.

**Comment by gjost** [comment]
Fixed in ddr-cmdln commit 1496af3 for package ddrlocal-develop_2.8.4b.

**Comment by pkikawa** [comment]
working in 286
