### ISSUE TITLE
ddrindex does not generate correct ES json `template` attribute for some A/V entities

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-cmdln#155]
When using `ddrindex publish` to push up some entities with audio/video content that is hosted externally at IA, the `template` attribute is not properly generated.

This is due to either empty or incorrect selection of mimetype data that is retrieved from IA by the `archivedotorg` module. See: 

https://github.com/densho/ddr-cmdln/blob/master/ddr/DDR/archivedotorg.py#L137
https://github.com/densho/ddr-cmdln/blob/master/ddr/DDR/archivedotorg.py#L131

**Comment by GeoffFroh** [comment]
related to https://github.com/densho/ddr-public/issues/123

**Comment by gjost** [comment]
Fixed in ddr-cmdln commit d4d23ae for package ddrlocal-master_2.8.5.
