### ISSUE TITLE
ddr-pubcopy should only copy files matching the selected DDR file roles

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-cmdln#161]
`ddr-pubcopy` currently has four flags to select file types -- `access`, `master`, `mezzanine`, and `transcript`. 

The command should only support the following DDR file roles:

- `master`
- `mezzanine`
- `transcript`
- `administrative`

When a role is selected, the command should copy both the binaries in that role and the matching access files (e.g., `ddr-densho-2-mezzanine-45aad3499c.tif` and `ddr-densho-2-mezzanine-45aad3499c-a.jpg`). 

As is the case now, the command should only copy binaries where the parent entity is `status`==`completed` and `public` == `1`, and the binary itself has `public` == `1`. (Enhancement: maybe a `--forceall` flag that copies unpublished, private binaries as well)

**Comment by gjost** [comment]
So, 
- Add an `--administrative` flag.
- Remove the `--access` flag.  Always copy access files for the requested file roles.
- Add a `--forceall` flag that bypasses `status` and `public` checks.

**Comment by gjost** [comment]
Note that `ddr-pubcopy` does not check `status` or `public` - it just copies whatever is there.  The helptext says to run this after filtering a collection.

**Comment by GeoffFroh** [comment]
We should have the command check `status` and `public` if possible. We haven't used `ddr-filter` in the publication workflow for several years. 

Please take a look at feasibility and time-required.

**Comment by gjost** [comment]
I can add the checks. Shouldn't take too long.

**Comment by gjost** [comment]
Fixed in ddr-cmdln commit 837b1ee for package ddrlocal-develop_2.8.8-2~deb9.

**Comment by gjost** [comment]
Fixed in ddr-cmdln commit 837b1ee for package ddrlocal-develop-2.8.8-2~deb9.

**Comment by pkikawa** [comment]
fixed in version 2.8.9 MA

**Comment by sarabeckman** [comment]
Successfully ran `ddr-pubcopy` on `ddr-develop_2.8.9-5`.
