### ISSUE TITLE
publishable files with unpublishable parents get published

### ISSUE THREAD

**Issue by gjost** [densho/ddr-cmdln#166]

**Comment by gjost** [comment]
Fixed in `ddr-cmdln` commit `8da6579` for package `ddrpublic-develop 3.2.9h~deb9`.

**Comment by gjost** [comment]
Ooops, need to update the tests.  It's not publishing ddr-densho-1000 entities properly for some reason.

**Comment by gjost** [comment]
Fixed in `ddr-cmdln` commit `73fa47d` for package `ddrlocal-develop_2.8.9-3~deb9`.

**Comment by sarabeckman** [comment]
Tested on ddrlocal-develop_2.8.9-3
Attempted to publish ddr-densho-1000-441 to ddrstage (interview status=inprocess with all segment status = completed). All segments skipped with "parent unpublishable" as expected.
