### ISSUE TITLE
ddr-pubcopy not copying files from original directory to target directory

### ISSUE THREAD

**Issue by sarabeckman** [densho/ddr-cmdln#167]
`ddr-pubcopy` output in 2.8.10 master:
[ddr-pubcopy_output_2810_MA.txt](https://github.com/densho/ddr-cmdln/files/3585194/ddr-pubcopy_output_2810_MA.txt)

`ddr-pubcopy` output in 2.8.9 MA 
[ddr-pubcopy_output_289_MA.txt](https://github.com/densho/ddr-cmdln/files/3585164/ddr-pubcopy_output_289_MA.txt)

In 2.8.10 MA the destination directory is created in `/media/qnfs/kinkura/transfer/` but no binary files are copied to it. The command calls for different arguments from previously. Listing the file types to copy instead of a flag. 

In 2.8.9 MA the binary files are successfully copied to the transfer directory. The command uses the old arguments the `-mat` flags.

**Comment by GeoffFroh** [comment]
related to #161

**Comment by sarabeckman** [comment]
Tested `ddr-pubcopy` on Maunakea (10.0.1.17)
We got the following Traceback error (in text document).
[ddr-pubcopy_output_Maunakea.txt](https://github.com/densho/ddr-cmdln/files/3585871/ddr-pubcopy_output_Maunakea.txt)

Geoff made a symlink between `/var/www/media/ddr` and `/media/qnfs/kinkura/gold/`. Once we did that we were able to verify and replicate the same results I got from my local VM running 2.8.10 MA.

**Comment by GeoffFroh** [comment]
Tested with the `ddr-densho-365` repo that @sarabeckman used in original issue test. Confirmed same behavior, however, using `--force` flag did work. 

There is likely something amiss with the logic in `can_publish`:

https://github.com/densho/ddr-cmdln/blob/master/ddr/bin/ddr-pubcopy#L116

Maybe a type mismatch with the `public` flags -- they are string values in `entity.json`

This gist might fix: https://gist.github.com/GeoffFroh/675dfd258299923f326b8ac5ea177354

**Comment by gjost** [comment]
Fixed in ddr-cmdln commit `58151d7` for package `ddrlocal-develop_2.8.9-4`.

**Comment by sarabeckman** [comment]
[ddr-pubcopy_traceback_28910Dev.txt](https://github.com/densho/ddr-cmdln/files/3591626/ddr-pubcopy_traceback_28910Dev.txt)
Ran `ddr-pubcopy` running `ddrlocal-develop_2.8.9-4` on my local VM.  I received the above Error Traceback.

**Comment by gjost** [comment]
This is a separate issue: https://github.com/densho/ddr-local/issues/265

**Comment by sarabeckman** [comment]
Successfully ran `ddr-pubcopy` on `ddr-develop_2.8.9-5`.
