### ISSUE TITLE
Discrepancies in local vs known annex keys,size

### ISSUE THREAD

**Issue by gjost** [densho/ddr-cmdln#19]
< geoff.froh at densho.org > 2015-05-19 10:50:

 Here's some additional followup on the odd git annex status behavior we were discussing yesterday. To summarize, in the group of ddr-njpa repos that I'm prepping for publication (ddr-njpa-1, ddr-njpa-2, ddr-njpa-4, ddr-njpa-6, ddr-njpa-8) when running git annex status, there is a discrepancy between "local annex keys"/"local annex size" vs. "known annex keys"/"known annex size". The "local" value are always less and approximately 50% of the "known" values. However, git annex whereis reports that all of the content that should exist is present in the local annex ("here"); in addition, git annex fsck is clean and git annex unused does not contain a large amount of data.

Sample output:
```
ddr@kinkura:/media/qnfs/kinkura/gold/ddr-njpa-1$ git annex status
...
local annex keys: 8764
local annex size: 17 gigabytes
known annex keys: 17530
known annex size: 35 gigabytes
...
git annex fsck: clean
git annex whereis: all OK; 1 copy here (qnfs)
```

Yesterday afternoon, I deleted the existing ddr-njpa-8 repo, and did a fresh recreate and reimport. For the recreate, I used the ddr-cmdln 'ddr create' command-line tool; the reimport used the ddr-local migration library on the current master branch. Both operations were using a fresh VM (deb 7.8) on the laptop dragontail connected to the qumulo. 

I ran ddrfilter and ddrpubcopy on the newly created repo and both worked as expected, producing the expected output data. However, git annex status shows exactly the same discrepancy as the other existing ones (i.e., "local" is almost exactly half of "known"). 

At this point, I'm going to do a larger sample of the other repos in gold to see if this behavior is more widespread.

Again, not sure if this really matters; although I've used git annex status as one way -- along with checking the output from the git annex get op, of course -- to verify that I've got all of a partner's data copied both at the remote site when prepping the drive and at HQ when pulling data into the gold repos on the qumulo.

**Comment by gjost** [comment]
< geoff.froh at densho.org > 2015-05-19 12:45:

I think I may have figured out some of what's going on -- we have some collections where the original scanned file was added twice: both as the master and the mezzanine file. This occurs in collections like some of the NJPA, where there were legacy scans that we are going to replace; but needed the lower-quality originals as placeholders.

I checked a few individual entities, and do see that there are two symlinks -- one named for the master file and one for the mezzanine file -- that are pointed at the same target.

Would this explain the discrepancy?

**Comment by gjost** [comment]
That's exactly the kind of thing I would expect to see.  In git-annex's terminology, "keys" are the symlinks that point to actual files in the object store.  I would expect to see two symlinks, with different names, that both point to the same SHA256-named file in the .git/annex/ objects directory.

Of course, given that the local size is exactly 50% of the known size, I would expect *all* the binaries in those collections to be like this.  If that's the case, then I'd say we have our explanation.

**Comment by GeoffFroh** [comment]
Confirmed that the repos in question had the exact same original binary in both the master and mezzanine roles -- two symlinks with different filenames pointed at the same SHA file in annex objects directory. Therefore, twice the number of keys and twice the size reported by git annex status. 

(FWIW, still seems strange that "local keys" refers to the number of *symlink targets*; while "known keys" seems to mean the total number of *symlinks*. It seemed more logical to me that "local keys" refers to the number of objects present in the local annex vs. "known keys," the total number of unique objects that are known to exist across all remotes. Otherwise, the only way to know what might be "missing" from the local annex is to run your own parsing against git annex whereis. But I didn't code it, so....)
