### ISSUE TITLE
ddr-export inserts extra newline chars in entity 'topics' value

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-cmdln#48]
When exporting entities and there is more than one value present in the 'topics' attribute, `ddr-export` inserts a spurious `\n` char for each subsequent KV pair in the list. Example:

`"term:Military service: Veterans' organizations|id:19;\nterm:World War II: Military service|id:88;\nterm:World War II: Military service: 100th Infantry Battalion|id:421",`

**Comment by gjost** [comment]
@GeoffFroh does it do this to the other listofdicts fields, e.g. facility, chronology, geology?

**Comment by gjost** [comment]
Should be fixed in commit d4f6468
