### ISSUE TITLE
ddrindex needs `narrators` command

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-cmdln#74]
The older publishing workflow had a `ddr-index narrators` command that parsed the narrators.json file and posted each individual narrator node in the document to the ES index. The new `ddrindex` command does not have that option (https://github.com/densho/ddr-cmdln/blob/9e36641706d3364722951fc28b539ef9924d1519/ddr/DDR/cli/ddrindex.py)

The original commit for the old functionality is: https://github.com/densho/ddr-cmdln/commit/29cb1cfd29146ce8251b4b6517207a60ed81b7b5

**Comment by gjost** [comment]
Restored to `develop` branch in commit 4c0071e.
