### ISSUE TITLE
ddr-import creates a spurious dir in `files` when importing an `external` File

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-cmdln#77]
ddr-import can import Files that are stored outside of the collection repo's git-annex. This is usually the case with VH video segments (housed at IA). External Files are identified by the value `"1"` in the `external` field of the import CSV file. 

ddr-import appears to create the external File's json in the parent Entity's `files/` directory and properly modifies the parent's `entity.json` as expected; but also creates an extra empty dir inside of `files/` that is named with the external File's identifier.

**Comment by gjost** [comment]
Can you give me an example line or two (with headers) from the CSV used for the import?

**Comment by GeoffFroh** [comment]
(Uploaded with the txt extension 'cause github doesn't take csv?! But xlsx and zip? Fantastic...)

[DDRIMPORT-ddr-densho-1004-11-files.csv.txt](https://github.com/densho/ddr-cmdln/files/2128561/DDRIMPORT-ddr-densho-1004-11-files.csv.txt)

**Comment by GeoffFroh** [comment]
FWIW, this does not seem to cause any issues with git/git-annex since the dirs are empty. I.e., they are just extra cruft in the local working dir.

**Comment by gjost** [comment]
Thanks for the sample data.  FWIW git/git-annex will ignore empty directories so they won't appear in clones.

**Comment by gjost** [comment]
Fixed in commit c60fcb4 on develop
