### ISSUE TITLE
(develop) ddrimport has bad url for downloading vocabs

### ISSUE THREAD

**Issue by sarabeckman** [densho/ddr-cmdln#85]
`ddrimport` command calls `vocab._get_vocabs_all_http` to retrieve the list of controlled vocabularies in order to validate the import csv file. See:

https://github.com/densho/ddr-cmdln/blob/bac19d6d051dc3b62cebac48a2a1c901f2d00c14/ddr/DDR/vocab.py#L599

The code attempts to concatenate 'index' to the base vocab url. The proper string is 'index.json'. (It also appears to use improper concatenation syntax...)

**Comment by gjost** [comment]
Version info from the affected machine:
```
Rendered at 2018-08-07T16:22:43.189953-07:00 by PID 29975 on DDREditor
loc: 4cc759ffbd942e1b7568dbf62f357d408685867a  (HEAD -> develop) 2018-07-06 13:37:20 -0700
cmd: 94cd31eb468046fe486be961d1b19f561494673f  (HEAD -> develop, origin/develop) 2018-07-06 13:35:32 -0700
def: 536051f90f74b545ae8c2633b29136383058b845  (HEAD -> develop, origin/develop) 2018-07-06 13:24:30 -0700
def: /opt/ddr-local/ddr-defs/
```

**Comment by gjost** [comment]
It would be more helpful if you could follow our standard bug report protocol, and tell me what you were trying to do, what happened instead, and then include an error message and traceback/stacktrace as well as the version info.

Your report is more of a diagnosis but it doesn't actually describe the problem you had.  I'm not saying it's bad for you guys to try to diagnose, but that should come after the evidence.

**Comment by gjost** [comment]
Version info from the affected machine:
```
Rendered at 2018-08-07T16:22:43.189953-07:00 by PID 29975 on DDREditor<br/>
loc: 4cc759ffbd942e1b7568dbf62f357d408685867a  (HEAD -> develop) 2018-07-06 13:37:20 -0700<br/>
cmd: 94cd31eb468046fe486be961d1b19f561494673f  (HEAD -> develop, origin/develop) 2018-07-06 13:35:32 -0700<br/>
def: 536051f90f74b545ae8c2633b29136383058b845  (HEAD -> develop, origin/develop) 2018-07-06 13:24:30 -0700<br/>
def: /opt/ddr-local/ddr-defs/<br/>
```

**Comment by gjost** [comment]
I'm unable to duplicate this in my development environment.  Can you tell me which commands provoked the error?

**Comment by sarabeckman** [comment]
I haven't been able to duplicate this bug since switching to the newest version of ddrlocal

**Comment by GeoffFroh** [comment]
This is the result of branch/version conflicts in the package that was deployed when the issue was first discovered.
