### ISSUE TITLE
ddrimport entity hanging on Identifier

### ISSUE THREAD

**Issue by sarabeckman** [densho/ddr-cmdln#90]
![ddrimportentitybug](https://user-images.githubusercontent.com/38959538/45109766-4ff91480-b0f5-11e8-8a27-bc8e719ea39a.JPG)

ddrimport entity is not moving past the first DDR.identifier.Identifier collection step. The process doesn't stop and I have to manually cancel out of the operation. 

I'm running master version 2.6.1 on my local VM. My local VM is also running stretch.

**Comment by gjost** [comment]
I confirmed that contents of the log on kinkura agree with the screenshot.  I copied the CSV to my local dev environment and ran it on a local copy of that collection but was not able to duplicate the error.

Before we do anything else, can you update your copy of ddrlocal?  I notice it's a couple versions behind.

**Comment by sarabeckman** [comment]
I updated my copy to version 2.6.3 and I tried running the same ddrimport entity command and I got the same result.

**Comment by gjost** [comment]
I've downloaded both the CSV (ddr-csujad-14-entities-20180501-1049.csv) and the repository itself from kinkura to my local system.  I also rolled back all the DDR components (ddr-defs, ddr-cmdln, ddr-local) to the where they are in 2.6.3 and recompiled everything from scratch.  Unfortunately I still haven't been able to duplicate this bug.

**Comment by gjost** [comment]
In future bug reports, it's better to cut-and-paste text from the terminal rather than take screenshots.  This makes it a lot easier to work with paths and stuff, cut-and-paste rather than squint and type.

**Comment by gjost** [comment]
I notice the command does not include the ID service username or password.  Did you have these in environment variables, e.g. `export IDSERVICE_ENVIRONMENT_USERNAME=redacted`?

**Comment by sarabeckman** [comment]
Aha! okay I added my ID service username and password to the command and the command worked!

**Comment by gjost** [comment]
Awesome! I guess i need to make it complain and quit if it doesnt have that info.

On September 7, 2018 11:51:56 AM PDT, Sara Beckman <notifications@github.com> wrote:
>Aha! okay I added my ID service username and password to the command
>and the command worked! 
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/densho/ddr-cmdln/issues/90#issuecomment-419532616

-- 
"Work as if you live in the early days of a better national. --Alasdair Gray

**Comment by gjost** [comment]
Fixed in 9906b50.
